### PR TITLE
Feature/em 533 preview thumbnail endpoint

### PR DESCRIPTION
**Pull request by alectronic0**

### CODE REVIEW

**Comment by pawelkaczmarekuk** [comment]
Spelling error in the method name ImageResizeService.apsectRatio

**Comment by pawelkaczmarekuk** [comment]
It'd seems that this could be quite resource hungry especially if the number of requests raise. Perhaps we should think of ways of storing/caching already generated thumbnails since they will never change after a Document upload.

**Comment by pawelkaczmarekuk** [comment]
AbstractFileSpecificThumbnailCreator.getThumbnail - inside of the method exceptions are caught and RuntimeException is thrown. Please avoid generic exceptions. Instead create a new class that extends RuntimeException with a meaningful name. Create a constructor with String msg, Throwable e and pass there the original Exception. Name of the class could be CantCreateThumbnailException or something like that.

**Comment by Louisblack** [comment]
Agree. We can either add cache headers for the browser and web server to cache.

**Comment by alectronic0** [comment]
for the cache header do I add it to the controller??

**Comment by alectronic0** [comment]
I will fix the run time exception soon

**Comment by Louisblack** [comment]
Here’s a good link talking about the various things you can set to help with caching -  http://www.nurkiewicz.com/2015/06/writing-download-server-part-ii-headers.html?m=1

**Comment by Louisblack** [comment]
And we can set some stuff in nginx to cache certain requests - https://www.nginx.com/blog/nginx-caching-guide/

**Comment by Louisblack** [comment]
Maybe those can be a separate task that iterate on this work though rather than blocking this PR.

**Comment by pawelkaczmarekuk** [comment]
Let's take a look together at the hierarchy of classes in uk.gov.hmcts.dm.service.thumbnail. I think it may be simplified.

**Comment by pawelkaczmarekuk** [comment]
I noticed your convention of naming a leaf class with a suffix 'Service' where its parent is 'Creator'. I find it confusing. I'd keep the Creator suffix of the parent. ie ImageResizeCreator instead of ImageResizeService (extends FileSpecificThumbnailCreator). The fact they are services does not mean their names have to end with the 'Service' suffix.

**Comment by pawelkaczmarekuk** [comment]
I agree that the caching issue can be solved in a separate ticket.

**Comment by pawelkaczmarekuk** [comment]
I'd remove ThumbnailCreator.supports(String mimeType) - it shouldn't be a part of the API.

**Pull request merged**
